### ISSUE TITLE
How to read excel file about information

### ISSUE THREAD

**Issue by CBNU-kimjimin** [IllllIIlI/ProjPrac#3]
An Excel file containing key information on electric vehicle charging stations has been prepared. How will we load the Excel file? Please leave your comments.

**Comment by aries043** [comment]
I would like to use Python's 'pandas' module.
Read Excel file using 'pd.read_excel'.
Store the line with the desired word in the 'address' index of the Excel file in an int-type variable.
Put the int type of variable into the index of the table from which it was read and output only the desired information.

**Comment by IllllIIlI** [comment]
It seems easy to implement with Python module.
I will check the other languages's modules and let you know.
